# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scoring_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15scoring_service.proto\x12\x07scoring\"\\\n\x08\x44\x61tabase\x12%\n\x02\x64\x62\x18\x01 \x03(\x0b\x32\x19.scoring.Database.DbEntry\x1a)\n\x07\x44\x62\x45ntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x08:\x02\x38\x01\"8\n\tFloorplan\x12\x1f\n\x06\x66igure\x18\x01 \x01(\x0b\x32\x0f.scoring.Figure\x12\n\n\x02id\x18\x02 \x01(\t\"\x17\n\x06\x46igure\x12\r\n\x05image\x18\x01 \x01(\x0c\"\xa0\x03\n\x05Graph\x12\x10\n\x08\x64irected\x18\x01 \x01(\x08\x12\x12\n\nmultigraph\x18\x02 \x01(\x08\x12=\n\x10graph_attributes\x18\x03 \x03(\x0b\x32#.scoring.Graph.GraphAttributesEntry\x1a\x36\n\x14GraphAttributesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1ak\n\tnode_info\x12\x31\n\x05nodes\x18\x01 \x03(\x0b\x32\".scoring.Graph.node_info.node_dict\x1a+\n\tnode_dict\x12\x0c\n\x04\x61rea\x18\x01 \x01(\x01\x12\x10\n\x08value_id\x18\x02 \x01(\t\x1a\x8c\x01\n\tlink_info\x12\x31\n\x05links\x18\x01 \x03(\x0b\x32\".scoring.Graph.link_info.link_dict\x1aL\n\tlink_dict\x12\r\n\x05\x63olor\x18\x01 \x01(\t\x12\x10\n\x08\x64istance\x18\x02 \x01(\x01\x12\x0e\n\x06source\x18\x03 \x01(\t\x12\x0e\n\x06target\x18\x04 \x01(\t\"\x9b\x01\n\x06Scores\x12\x18\n\x10score_commonarea\x18\x01 \x01(\x01\x12\x18\n\x10score_functional\x18\x02 \x01(\x01\x12\x16\n\x0escore_corridor\x18\x03 \x01(\x01\x12\"\n\x1ascore_connectivity_private\x18\x04 \x01(\x01\x12!\n\x19score_connectivity_public\x18\x05 \x01(\x01\x32\xae\x01\n\x07Scoring\x12\x38\n\x0bGetNewGraph\x12\x11.scoring.Database\x1a\x12.scoring.Floorplan\"\x00\x30\x01\x12\x35\n\rGenerateGraph\x12\x12.scoring.Floorplan\x1a\x0e.scoring.Graph\"\x00\x12\x32\n\rGenerateScore\x12\x0e.scoring.Graph\x1a\x0f.scoring.Scores\"\x00\x62\x06proto3')



_DATABASE = DESCRIPTOR.message_types_by_name['Database']
_DATABASE_DBENTRY = _DATABASE.nested_types_by_name['DbEntry']
_FLOORPLAN = DESCRIPTOR.message_types_by_name['Floorplan']
_FIGURE = DESCRIPTOR.message_types_by_name['Figure']
_GRAPH = DESCRIPTOR.message_types_by_name['Graph']
_GRAPH_GRAPHATTRIBUTESENTRY = _GRAPH.nested_types_by_name['GraphAttributesEntry']
_GRAPH_NODE_INFO = _GRAPH.nested_types_by_name['node_info']
_GRAPH_NODE_INFO_NODE_DICT = _GRAPH_NODE_INFO.nested_types_by_name['node_dict']
_GRAPH_LINK_INFO = _GRAPH.nested_types_by_name['link_info']
_GRAPH_LINK_INFO_LINK_DICT = _GRAPH_LINK_INFO.nested_types_by_name['link_dict']
_SCORES = DESCRIPTOR.message_types_by_name['Scores']
Database = _reflection.GeneratedProtocolMessageType('Database', (_message.Message,), {

  'DbEntry' : _reflection.GeneratedProtocolMessageType('DbEntry', (_message.Message,), {
    'DESCRIPTOR' : _DATABASE_DBENTRY,
    '__module__' : 'scoring_service_pb2'
    # @@protoc_insertion_point(class_scope:scoring.Database.DbEntry)
    })
  ,
  'DESCRIPTOR' : _DATABASE,
  '__module__' : 'scoring_service_pb2'
  # @@protoc_insertion_point(class_scope:scoring.Database)
  })
_sym_db.RegisterMessage(Database)
_sym_db.RegisterMessage(Database.DbEntry)

Floorplan = _reflection.GeneratedProtocolMessageType('Floorplan', (_message.Message,), {
  'DESCRIPTOR' : _FLOORPLAN,
  '__module__' : 'scoring_service_pb2'
  # @@protoc_insertion_point(class_scope:scoring.Floorplan)
  })
_sym_db.RegisterMessage(Floorplan)

Figure = _reflection.GeneratedProtocolMessageType('Figure', (_message.Message,), {
  'DESCRIPTOR' : _FIGURE,
  '__module__' : 'scoring_service_pb2'
  # @@protoc_insertion_point(class_scope:scoring.Figure)
  })
_sym_db.RegisterMessage(Figure)

Graph = _reflection.GeneratedProtocolMessageType('Graph', (_message.Message,), {

  'GraphAttributesEntry' : _reflection.GeneratedProtocolMessageType('GraphAttributesEntry', (_message.Message,), {
    'DESCRIPTOR' : _GRAPH_GRAPHATTRIBUTESENTRY,
    '__module__' : 'scoring_service_pb2'
    # @@protoc_insertion_point(class_scope:scoring.Graph.GraphAttributesEntry)
    })
  ,

  'node_info' : _reflection.GeneratedProtocolMessageType('node_info', (_message.Message,), {

    'node_dict' : _reflection.GeneratedProtocolMessageType('node_dict', (_message.Message,), {
      'DESCRIPTOR' : _GRAPH_NODE_INFO_NODE_DICT,
      '__module__' : 'scoring_service_pb2'
      # @@protoc_insertion_point(class_scope:scoring.Graph.node_info.node_dict)
      })
    ,
    'DESCRIPTOR' : _GRAPH_NODE_INFO,
    '__module__' : 'scoring_service_pb2'
    # @@protoc_insertion_point(class_scope:scoring.Graph.node_info)
    })
  ,

  'link_info' : _reflection.GeneratedProtocolMessageType('link_info', (_message.Message,), {

    'link_dict' : _reflection.GeneratedProtocolMessageType('link_dict', (_message.Message,), {
      'DESCRIPTOR' : _GRAPH_LINK_INFO_LINK_DICT,
      '__module__' : 'scoring_service_pb2'
      # @@protoc_insertion_point(class_scope:scoring.Graph.link_info.link_dict)
      })
    ,
    'DESCRIPTOR' : _GRAPH_LINK_INFO,
    '__module__' : 'scoring_service_pb2'
    # @@protoc_insertion_point(class_scope:scoring.Graph.link_info)
    })
  ,
  'DESCRIPTOR' : _GRAPH,
  '__module__' : 'scoring_service_pb2'
  # @@protoc_insertion_point(class_scope:scoring.Graph)
  })
_sym_db.RegisterMessage(Graph)
_sym_db.RegisterMessage(Graph.GraphAttributesEntry)
_sym_db.RegisterMessage(Graph.node_info)
_sym_db.RegisterMessage(Graph.node_info.node_dict)
_sym_db.RegisterMessage(Graph.link_info)
_sym_db.RegisterMessage(Graph.link_info.link_dict)

Scores = _reflection.GeneratedProtocolMessageType('Scores', (_message.Message,), {
  'DESCRIPTOR' : _SCORES,
  '__module__' : 'scoring_service_pb2'
  # @@protoc_insertion_point(class_scope:scoring.Scores)
  })
_sym_db.RegisterMessage(Scores)

_SCORING = DESCRIPTOR.services_by_name['Scoring']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATABASE_DBENTRY._options = None
  _DATABASE_DBENTRY._serialized_options = b'8\001'
  _GRAPH_GRAPHATTRIBUTESENTRY._options = None
  _GRAPH_GRAPHATTRIBUTESENTRY._serialized_options = b'8\001'
  _DATABASE._serialized_start=34
  _DATABASE._serialized_end=126
  _DATABASE_DBENTRY._serialized_start=85
  _DATABASE_DBENTRY._serialized_end=126
  _FLOORPLAN._serialized_start=128
  _FLOORPLAN._serialized_end=184
  _FIGURE._serialized_start=186
  _FIGURE._serialized_end=209
  _GRAPH._serialized_start=212
  _GRAPH._serialized_end=628
  _GRAPH_GRAPHATTRIBUTESENTRY._serialized_start=322
  _GRAPH_GRAPHATTRIBUTESENTRY._serialized_end=376
  _GRAPH_NODE_INFO._serialized_start=378
  _GRAPH_NODE_INFO._serialized_end=485
  _GRAPH_NODE_INFO_NODE_DICT._serialized_start=442
  _GRAPH_NODE_INFO_NODE_DICT._serialized_end=485
  _GRAPH_LINK_INFO._serialized_start=488
  _GRAPH_LINK_INFO._serialized_end=628
  _GRAPH_LINK_INFO_LINK_DICT._serialized_start=552
  _GRAPH_LINK_INFO_LINK_DICT._serialized_end=628
  _SCORES._serialized_start=631
  _SCORES._serialized_end=786
  _SCORING._serialized_start=789
  _SCORING._serialized_end=963
# @@protoc_insertion_point(module_scope)
