# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scoring_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15scoring_service.proto\x12\x07scoring\"\x1e\n\x04time\x12\x0b\n\x03\x64\x61y\x18\x01 \x01(\t\x12\t\n\x01t\x18\x02 \x01(\t\"/\n\tFloorplan\x12\x16\n\x0e\x66loorplan_path\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\"e\n\tnode_info\x12+\n\x05nodes\x18\x01 \x03(\x0b\x32\x1c.scoring.node_info.node_dict\x1a+\n\tnode_dict\x12\x0c\n\x04\x61rea\x18\x01 \x01(\x01\x12\x10\n\x08value_id\x18\x02 \x01(\t\"\x86\x01\n\tlink_info\x12+\n\x05links\x18\x01 \x03(\x0b\x32\x1c.scoring.link_info.link_dict\x1aL\n\tlink_dict\x12\r\n\x05\x63olor\x18\x01 \x01(\t\x12\x10\n\x08\x64istance\x18\x02 \x01(\x01\x12\x0e\n\x06source\x18\x03 \x01(\t\x12\x0e\n\x06target\x18\x04 \x01(\t\"\xea\x01\n\x05Graph\x12\x10\n\x08\x64irected\x18\x01 \x01(\x08\x12\x12\n\nmultigraph\x18\x02 \x01(\x08\x12=\n\x10graph_attributes\x18\x03 \x03(\x0b\x32#.scoring.Graph.GraphAttributesEntry\x12!\n\x05nodes\x18\x04 \x01(\x0b\x32\x12.scoring.node_info\x12!\n\x05links\x18\x05 \x01(\x0b\x32\x12.scoring.link_info\x1a\x36\n\x14GraphAttributesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x9b\x01\n\x06Scores\x12\x18\n\x10score_commonarea\x18\x01 \x01(\x01\x12\x18\n\x10score_functional\x18\x02 \x01(\x01\x12\x16\n\x0escore_corridor\x18\x03 \x01(\x01\x12\"\n\x1ascore_connectivity_private\x18\x04 \x01(\x01\x12!\n\x19score_connectivity_public\x18\x05 \x01(\x01\x32\xaa\x01\n\x07Scoring\x12\x34\n\x0bGetNewGraph\x12\r.scoring.time\x1a\x12.scoring.Floorplan\"\x00\x30\x01\x12\x35\n\rGenerateGraph\x12\x12.scoring.Floorplan\x1a\x0e.scoring.Graph\"\x00\x12\x32\n\rGenerateScore\x12\x0e.scoring.Graph\x1a\x0f.scoring.Scores\"\x00\x62\x06proto3')



_TIME = DESCRIPTOR.message_types_by_name['time']
_FLOORPLAN = DESCRIPTOR.message_types_by_name['Floorplan']
_NODE_INFO = DESCRIPTOR.message_types_by_name['node_info']
_NODE_INFO_NODE_DICT = _NODE_INFO.nested_types_by_name['node_dict']
_LINK_INFO = DESCRIPTOR.message_types_by_name['link_info']
_LINK_INFO_LINK_DICT = _LINK_INFO.nested_types_by_name['link_dict']
_GRAPH = DESCRIPTOR.message_types_by_name['Graph']
_GRAPH_GRAPHATTRIBUTESENTRY = _GRAPH.nested_types_by_name['GraphAttributesEntry']
_SCORES = DESCRIPTOR.message_types_by_name['Scores']
time = _reflection.GeneratedProtocolMessageType('time', (_message.Message,), {
  'DESCRIPTOR' : _TIME,
  '__module__' : 'scoring_service_pb2'
  # @@protoc_insertion_point(class_scope:scoring.time)
  })
_sym_db.RegisterMessage(time)

Floorplan = _reflection.GeneratedProtocolMessageType('Floorplan', (_message.Message,), {
  'DESCRIPTOR' : _FLOORPLAN,
  '__module__' : 'scoring_service_pb2'
  # @@protoc_insertion_point(class_scope:scoring.Floorplan)
  })
_sym_db.RegisterMessage(Floorplan)

node_info = _reflection.GeneratedProtocolMessageType('node_info', (_message.Message,), {

  'node_dict' : _reflection.GeneratedProtocolMessageType('node_dict', (_message.Message,), {
    'DESCRIPTOR' : _NODE_INFO_NODE_DICT,
    '__module__' : 'scoring_service_pb2'
    # @@protoc_insertion_point(class_scope:scoring.node_info.node_dict)
    })
  ,
  'DESCRIPTOR' : _NODE_INFO,
  '__module__' : 'scoring_service_pb2'
  # @@protoc_insertion_point(class_scope:scoring.node_info)
  })
_sym_db.RegisterMessage(node_info)
_sym_db.RegisterMessage(node_info.node_dict)

link_info = _reflection.GeneratedProtocolMessageType('link_info', (_message.Message,), {

  'link_dict' : _reflection.GeneratedProtocolMessageType('link_dict', (_message.Message,), {
    'DESCRIPTOR' : _LINK_INFO_LINK_DICT,
    '__module__' : 'scoring_service_pb2'
    # @@protoc_insertion_point(class_scope:scoring.link_info.link_dict)
    })
  ,
  'DESCRIPTOR' : _LINK_INFO,
  '__module__' : 'scoring_service_pb2'
  # @@protoc_insertion_point(class_scope:scoring.link_info)
  })
_sym_db.RegisterMessage(link_info)
_sym_db.RegisterMessage(link_info.link_dict)

Graph = _reflection.GeneratedProtocolMessageType('Graph', (_message.Message,), {

  'GraphAttributesEntry' : _reflection.GeneratedProtocolMessageType('GraphAttributesEntry', (_message.Message,), {
    'DESCRIPTOR' : _GRAPH_GRAPHATTRIBUTESENTRY,
    '__module__' : 'scoring_service_pb2'
    # @@protoc_insertion_point(class_scope:scoring.Graph.GraphAttributesEntry)
    })
  ,
  'DESCRIPTOR' : _GRAPH,
  '__module__' : 'scoring_service_pb2'
  # @@protoc_insertion_point(class_scope:scoring.Graph)
  })
_sym_db.RegisterMessage(Graph)
_sym_db.RegisterMessage(Graph.GraphAttributesEntry)

Scores = _reflection.GeneratedProtocolMessageType('Scores', (_message.Message,), {
  'DESCRIPTOR' : _SCORES,
  '__module__' : 'scoring_service_pb2'
  # @@protoc_insertion_point(class_scope:scoring.Scores)
  })
_sym_db.RegisterMessage(Scores)

_SCORING = DESCRIPTOR.services_by_name['Scoring']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GRAPH_GRAPHATTRIBUTESENTRY._options = None
  _GRAPH_GRAPHATTRIBUTESENTRY._serialized_options = b'8\001'
  _TIME._serialized_start=34
  _TIME._serialized_end=64
  _FLOORPLAN._serialized_start=66
  _FLOORPLAN._serialized_end=113
  _NODE_INFO._serialized_start=115
  _NODE_INFO._serialized_end=216
  _NODE_INFO_NODE_DICT._serialized_start=173
  _NODE_INFO_NODE_DICT._serialized_end=216
  _LINK_INFO._serialized_start=219
  _LINK_INFO._serialized_end=353
  _LINK_INFO_LINK_DICT._serialized_start=277
  _LINK_INFO_LINK_DICT._serialized_end=353
  _GRAPH._serialized_start=356
  _GRAPH._serialized_end=590
  _GRAPH_GRAPHATTRIBUTESENTRY._serialized_start=536
  _GRAPH_GRAPHATTRIBUTESENTRY._serialized_end=590
  _SCORES._serialized_start=593
  _SCORES._serialized_end=748
  _SCORING._serialized_start=751
  _SCORING._serialized_end=921
# @@protoc_insertion_point(module_scope)
